"""rename job listing to job application

Revision ID: 8a0abd756e81
Revises: 9258b32581dc
Create Date: 2023-11-20 22:49:26.738587

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "8a0abd756e81"
down_revision = "9258b32581dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("job_listing", "job_application")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("job_application", "job_listing")
    # ### end Alembic commands ###
